disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

included:
  - DynamicTime
  - DynamicTimeWidget
  - DynamicTimeTests
  - DynamicTimeUITests

excluded:
  - Carthage
  - Pods
  - SwiftLint/Common/3rdPartyLib

analyzer_rules:
  - explicit_self

force_cast: warning
force_try:
  severity: warning

function_body_length:
  warning: 100
  error: 150

large_tuple:
  warning: 3
  error: 4

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"